### ISSUE TITLE
点击无反应

### ISSUE THREAD

**Issue by hezhico** [emaction/emaction.frontend#1]
<html lang="en">
<head>
  <meta charset="UTF-8">

  <title>Document</title>

</head>
<body>
  <script type="module" src="https://cdn.jsdelivr.net/gh/emaction/frontend.dist@1.0.7/bundle.js"></script>
  <emoji-reaction ></emoji-reaction>
</body>
</html>

**Comment by eallion** [comment]
现在才 1.0.4 版本。

**Comment by tiezhudotwang** [comment]
可以参考下 [demo](https://github.com/emaction/emaction.cool) 页面的代码，应该是可以的。

还是不行的话，可以贴一下完整的页面代码，我这边复现试试~

**Comment by tiezhudotwang** [comment]
这个 issue 先关了哈，还有问题可以再次打开。
