### ISSUE TITLE
请教下，怎么覆盖样式，譬如调整.reaction-available-popup位置

### ISSUE THREAD

**Issue by koobai** [emaction/emaction.frontend#2]
请教下，怎么可以覆盖样式，譬如我要把.reaction-available-popup调整下位置，加个right: 0 !important;。目前直接加在自己的样式表中是无效的。Shadow DOM 的元素不受外部的样式影响。

**Comment by koobai** [comment]
另外想单独定义下emoji表情的大小，也是无法自定义。
当然最方便的就是把 JS 文件放本地，直接改 JS 里面的样式就行。但这不方便今后维护更新～
还请帮忙看看怎么修改，或者把这些都以变量的方式加在 JS 里，这样就可以直接修改.reactions {}里的样式了～

**Comment by tiezhudotwang** [comment]
之前看别的支持自定义样式的 web component，好像是会用到 slot 之类的东西，我研究研究，找时间更新下~

**Comment by tiezhudotwang** [comment]
看了一圈，发现 Lit 里貌似没有合适的方式，把所有 style 都开放出来，供外部自定义。好像只能挨个做成变量，但这样有点不太符合这个项目的目标，目前只是想做一个类似 github 的 emoji reaction 风格的东西。

如果你发现有什么方式，可以方便的把所有 style 开放出来，或者有任何想法，都可以告诉我，我看能否集成进来~

如果想调整 `.reaction-available-popup` 位置，可以 folk 下仓库，自己改吧改吧自己用~
