### ISSUE TITLE
how to adjust the style of the main button

### ISSUE THREAD

**Issue by simech-tech** [emaction/emaction.frontend#3]
Thank you for the great component. 
I inserted it into my blog page, but the position of the background of the main button is innormal, as shown in the figure, and I can not find a way to adjust it, any hint? Thanks.

![image](https://github.com/emaction/emaction.frontend/assets/16507701/4bc18565-51ea-4396-a978-2a7b596a0d64)

**Comment by tiezhudotwang** [comment]
Looks like it's related to the device resolution.

Could you help me test something - in devtools, change the svg element's width and height to 1rem and see if the display becomes correct. 

![image](https://github.com/emaction/emaction.frontend/assets/126638121/53120b66-a0f8-4058-af01-a4a59aa52a34)

**Comment by simech-tech** [comment]
Yes, it works by changing the height and width to 1rem, thanks!

**Comment by tiezhudotwang** [comment]
Version 1.0.8 fixed this~
