### ISSUE TITLE
不能设置样式

### ISSUE THREAD

**Issue by eallion** [emaction/emaction.frontend#4]
试过很多方法，纯前端 CSS 排版都不能正常显示。
![QQ截图20230805173330](https://github.com/emaction/emaction.frontend/assets/1698841/a56614e0-17db-4621-95ed-efd0b1626271)

我的预期效果是这样的：
![QQ截图20230805173231](https://github.com/emaction/emaction.frontend/assets/1698841/2fbf28fd-0e0d-4190-b496-25ea2dd0a6a5)

除非把`frontend.dist@1.0.4/bundle.js`下载下来放到本地，修改js内的代码。

**Comment by tiezhudotwang** [comment]
可否分享下出现问题的网页（或者能复现问题的 html），以及把修改后的代码分享下，我修复下这个bug

**Comment by eallion** [comment]
刚试了下，还能复现，就是我现在的 Hugo 博客。

https://github.com/eallion/eallion.com/blob/227212e83a49a0713c8f74cc1fe21a4c8023075e/layouts/_default/toot.html#L74

```diff
- <script type="module" src="/assets/toot/reactions.min.js?v=1.0.4"></script>
+ <script type="module" src="https://cdn.jsdelivr.net/gh/emaction/frontend.dist@1.0.8/bundle.js"></script>
```

修改后的代码在 `static/assets/toot/reactions.js`
- https://github.com/eallion/eallion.com/blob/main/static/assets/toot/reactions.js

**Comment by eallion** [comment]
如果想自己试也可以：
```bash
git clone https://github.com/eallion/eallion.com.git
git submodule update --init --recursive
hugo server -w -D --contentDir example
```
- http://127.0.0.1:1313/toot

**Comment by tiezhudotwang** [comment]
更新了`1.0.9`，试下好了没
```
<script type="module" src="https://cdn.jsdelivr.net/gh/emaction/frontend.dist@1.0.9/bundle.js"></script>
```

**Comment by tiezhudotwang** [comment]
另外，我看你的[这篇文章](https://eallion.com/self-hosted-github-flavored-reactions/)啦，放到了[后端文档](https://github.com/emaction/emaction.backend)里。

我看文章最后提到：

> reacttargetid 这个参数在各个版本有变化，1.0.7 版本它叫 reacttargetid。

我没太明白这是指哪里，方便细说下吗，这样我以后也能避免字段不兼容。

**Comment by eallion** [comment]
还是不行。

![动画12](https://github.com/emaction/emaction.frontend/assets/1698841/55d5432d-aacb-4349-b0dc-45621ec69b65)

**Comment by eallion** [comment]
> 另外，我看你的[这篇文章](https://eallion.com/self-hosted-github-flavored-reactions/)啦，放到了[后端文档](https://github.com/emaction/emaction.backend)里。
> 
> 我看文章最后提到：
> 
> > reacttargetid 这个参数在各个版本有变化，1.0.7 版本它叫 reacttargetid。
> 
> 我没太明白这是指哪里，方便细说下吗，这样我以后也能避免字段不兼容。

非常感谢！

当时每个版本都试了一下，某一个版本传参 `reacttargetid` 会提示 undefined 。

**Comment by tiezhudotwang** [comment]
> 如果想自己试也可以：
> 
> ```shell
> git clone https://github.com/eallion/eallion.com.git
> git submodule update --init --recursive
> hugo server -w -D --contentDir example
> ```
> 
> * http://127.0.0.1:1313/toot

@eallion  本地跑的时候，有些 js 文件和 api 接口报 403，应该是跨域设置里没允许 localhost:1313，方便的话改下，我来继续搞搞这个 bug

![image](https://github.com/emaction/emaction.frontend/assets/126638121/7899f335-a281-46a1-869d-029d8c173da8)

**Comment by eallion** [comment]
@tiezhudotwang 已经添加了 `127.0.0.1` ，5分钟之内应该就能刷新。

**Comment by tiezhudotwang** [comment]
@eallion  这回绝对 ok 了，再试试，1.0.10

```js
<script type="module" src="https://cdn.jsdelivr.net/gh/emaction/frontend.dist@1.0.10/bundle.js"></script>
```

**Comment by eallion** [comment]
> @eallion 这回绝对 ok 了，再试试，1.0.10

已经可以用了，不过还可以微调一下，总感觉没对齐。
![QQ截图20230828201112](https://github.com/emaction/emaction.frontend/assets/1698841/26361a16-2ee3-48b4-a1bc-6c3d7b669f7f)

**Comment by tiezhudotwang** [comment]
@eallion 

你小名是不是叫列文虎克😂

我搞了搞，有点头大，先让笑脸上下居中了，这样至少看着还舒服点

新版本`1.0.11`

**Comment by eallion** [comment]
@tiezhudotwang 完美了！非常感谢！
