### ISSUE TITLE
请问点击数据如何传递给后端

### ISSUE THREAD

**Issue by kemisstep** [emaction/emaction.frontend#5]
api接口怎么写？可以给个示例吗

**Comment by koobai** [comment]
可以参照这位博友的教程  https://eallion.com/self-hosted-github-flavored-reactions/

**Comment by tiezhudotwang** [comment]
> 可以参照这位博友的教程 https://eallion.com/self-hosted-github-flavored-reactions/

@koobai  哇，好奇妙的感觉，原来在我不知道的地方有这么些人在讨论、使用这个项目😎😎😎


> api接口怎么写？可以给个示例吗

@kemisstep  后端文档在写啦，争取今天更新上去~

**Comment by tiezhudotwang** [comment]
@kemisstep 后端文档写好啦，可以参考下，https://github.com/emaction/emaction.backend
