### ISSUE TITLE
请问后端能部署到服务器上吗，我看目前是在cf上。

### ISSUE THREAD

**Issue by dianso** [emaction/emaction.frontend#6]
请问后端能部署到服务器上吗，我看目前是在cf上。

**Comment by tiezhudotwang** [comment]
稍后我更新个后端文档~

**Comment by tiezhudotwang** [comment]
@dianso 后端文档写好啦，可以参考里边的接口文档，自己实现一个后端，放到服务器上，https://github.com/emaction/emaction.backend

**Comment by dianso** [comment]
> @dianso 后端文档写好啦，可以参考里边的接口文档，自己实现一个后端，放到服务器上，https://github.com/emaction/emaction.backend

非常感谢
