### ISSUE TITLE
在Safari浏览器中，会出现横向滚动条，而在chrome浏览器中则是正常的。

### ISSUE THREAD

**Issue by osirismin** [emaction/emaction.frontend#7]
在Safari浏览器中，会出现横向滚动条，而在Chrome浏览器中则是正常的。
![Safari浏览器](https://github.com/emaction/emaction.frontend/assets/86836865/ca8ab534-5f31-413a-ab12-5ad0928f1441)
![chrome浏览器](https://github.com/emaction/emaction.frontend/assets/86836865/2c938001-fcc4-4649-9806-b92d1b936c99)

**Comment by tiezhudotwang** [comment]
发了个新版本`1.0.11`，直接把 scroll 去掉了，一般也弄不了那么多 emoji
